abhishekdoifode1/Hacktoberfest2020

Stone Paper Scissor

Create Stone Paper Scissor

---

Astrologer's Stars

Create Astrologer's Stars

---

guess the number

Create guess the number

---

Dijkstra's shortest path algorithm

Create Dijkstra's shortest path algorithm

---

Fast Exponentiation

Create Fast Exponentiation

---

Even and Odd

Create Even and Odd

---

Kruskal's Minimum Spanning Algorithm

Create Kruskal's Minimum Spanning Algorithm

---

bubble sort

Create bubble sort

---

Hand Cricket

Create Hand Cricket

---

KMP Algorithm for pattern searching

Create KMP Algorithm for pattern searching

---

juggling algorithm

Create juggling algorithm

---

insertion sort

Create insertion sort

---

areaoftriangle.py

Python program To calculate a Area of a Triangle

areaoftriangle.py

---

helloWorld.c

Added hello world program in C.

hello world

---

simpleinterest.py

Simple interest program by Akshay

simpleinterest.py

---

textSpeak.py

Python Text-To-Speech Program. @abhishekdoifode1 My contribution to Open-Source

Text_To_Speech Python Program

---

sudoku.cpp

It's an old game code with an appropriate indentation for understanding

added a sudoku game

---

ASCIIvalue.py
Fibonacci_recursion.py

Added 2 programs

---

hammingdistance.py

I have added the solution to hamming distance leetcode problem, please merge if it seems good!

Added hamming distance leetcode problem

---

MissingNumber.java

Given an array of size n-1, find the missing number in [1-n]
the array contains no duplicate numbers
dhanueshrc

Missing Number

---

MissingNumber.java

I know it's not significant but I am a begginer just trying out open source.

Added some more explaination

---

anagram_or_not.py

This is a simple python program which check whether two given strings are anagram or not

Added python program to check whether a string is Anagram or not

---

password_generator.py

Added a simple random password generator made with python tkinter.

Simple random password generator with GUI

---

fibInJava.java

Added fibInJava

---

Knuth–Morris–Pratt algorithm.py

Kindly reviw the code and merge the PR.

Added KMP Algorithm

---

Snake-Game.py

Added algorithm game in Python.

Python script game Snake

---

DrawFlowerPython.py

Hi I'm drawing a flower with python here

Draw flower with python

---

Palindrome_check.py

Taking a number and checking if the  number is a Palindrome Number

Palindrome Check

---

expression_matching_using_stack.py

The expressions can have alphabetical variables and +/- as operators.
Sample i/o:
input1:
a+b+c  
-(a+b+c)
output1:
No
input2:
a+b+c
-(-a-b-c)
output2:
Yes
input3:
x+y-(z+p)
-z+x-x+x-p+y
output3:
Yes

This program checks if two expressions are same.

---

number_guess.py

Added number guessing game in Python.

add number guess script

---

variableFizzBuzz.cs

set value for fizz and buzz, program outputs custom fizzBuzz 1-100

lucasTheThompson - variableFizzBuzz

---

simpleinterest.py

Added Input options so that user can enter its own p, r and t

Get input from user

---

ClassesOne.py

An OOP example

---

Arr4 right shift.c
Array_in_C.c
Remove-Dublicate.js
Remove-Duplicates-from-Sorted-Array.c
Remove-Duplicates-from-Sorted-Array.cpp
Shuffle.c
Two-Arrays-And-Swaps.c
check_two_equal_array.cpp
copyarray.c
largest-smallest-number-and-sum-of-all-elements-in-array.java
merging_2_arrays.c
revering_array.c

Hey added various array programs. Please merge my PR and help me contribute open source.

added various array programs

---

QuadraticEquation.py

Quadratic Equation's roots solver By Faiz Alam

Finding roots of Quadratic Equation

---

multiplicationTable_sloth59.java

created a simple multiplication table in java with proper formatting

added a multiplication table in java

---

binomialheap.c
iterativebubblesort.c
iterativeinsertionsort.c
iterativeselectionsort.c
kruskals.c
maximumsubarraysum.c
medianofmedians.c
prims.c
recursivebubblesort.c
recursiveinsertionsort.c
recursiveselectionsort.c

I've added basic DSA codes written in C language.

added basic DSA algos in C language

---

IsPrime.cs

Added code to check for prime numbers in C#

Added IsPrime.cs

---

Stack Using Linked list.cpp

The implementation of Stack data structure using linked list has been added. I have added comments wherever necessary so that its easy to understand for anyone who is just starting out for learning data structures, or  if someone wants to take a look at others' codes.
Thanks.

Stack using Linked List added

---

rock_paper_scissors.py

Console version of rock paper scissor. :)

CLI based rock paper scissor - Sonu

---

crossyroad/game.cc
crossyroad/game.h

Famous android game written in c code

crossyroad in c code

---

Xstarpattern.c

I have added a new C program.I hope you would merge my pull request and mark it as hacktoberfest accepted as I am new to open source and contributing. Thank you.

Ajay055-New C program Added

---

GetMyIPAddress.java

Write the program in java for get the ip address
Program written by Kunal Pitale

GetMyIPAddress.java

---

Count_Vowels.py

Program to count number of vowels!!

Counting_vowels.py

---

Guessing_Game_Human_vs_CPU.java

Please do add the "hacktoberfest-accepted" tag.
Thank You.

Guessing Number Game Human v/s CPU in java (Abhijeet)

---

HelloWorldJava.java

[proposed Label]hacktoberfest - My hello hacktoberfest by Antoine Meyer

---

rodcuttingproblem.cpp

Given a rod of length n inches and an array of prices that contains prices of all pieces of size smaller than n. Determine the maximum value obtainable by cutting up the rod and selling the pieces.

maximumPriceByCuttingRod

---

Affine_Cipher.cpp

Encryption Algorithm for encryption and decryption (Affine cipher-substituion cipher)

Added Affine Cipher in C++

---

Floyd_Warshall.py

Floyd warshall algorithm to find minimum distance between all pair of points in a positive edged,weighted and directed graph.

Added Floyd Warshall algorithm in python

---

operator_overloading._by _Ananyac++

This program shows the concept of operator overloading

Create operator_overloading._by _Ananyac++

---

palindrom.ps1

Hi @abhishekdoifode1 ,
added a Powershell script to check text for palindromes.
thank you and kind regards,
Christopher

added ps1 palindrom script

---

Haversine.js

Haversine formula is used to calculate distance between two coords on earth. Useful for Google Roads API.

Haversine formula added

---

Armstrong in C

Create Armstrong in C

---

Email validation in JS

Email validation in JS with regex

JS email validation

---

TCS_CodeVita2020_CountPairs.py

Added TCS Codevita 2020 Count Pairs Solution in python

Add TCS Codevita 2020 Count Pairs Solution

---

Star patterns/Flyod's triangle

Dashminder adding Flyod's triangle

---

killjoy - CF

Codeforces problem Killjoy solution by Rachit Awasthi

Added killjoy - CF

---

Even and Odd

Removed syntax error in print statement of result. Inserted extra check to display and indicate Even and Odd numbers separately using if condition

Update Even and Odd

---

prims.cpp
prims.py

Added Prims Algorithm in CPP and Python

Kaustubh Shrivastava - Prims Algo in CPP and Python

---

Lost Array.cpp

Lost Array.cpp

---

indonesianCurrencyFormatNumber.php

create indonesianCurrencyFormatNumber.php file.

Ramdani Surya: add indonesianCurrencyFormatNumber.php

---

abhishekdoifode1

I have added the code for the addition of edge in a graph. I have done it in python.

coder122addition

---

java-programs/HammingDistance.java
java-programs/Islandperimeter.java
java-programs/UglyNumber.java

Hi,
Happy to contribute to this project.
Added algorithm implementation questions along with solutions as my first-time open source contribution.
wish to contribute similar more to this project.
Thanks

Java algorithm implementation programs - SMHari

---

RockPaperScissorsSpockLizard.py

A simple game of rock, paper, scissors in need of some touch ups

Added a Pyhton game

---

Triangular pattern

Create Triangular pattern

---

Armstrong in C
helloWorld.c

Updated Armstrong in C//

---

seive_of_eratosthenis.cpp
tower_of_hanoi.cpp

C++ implementation of tower of hanoi using recursion.

Added tower of hanoi cpp code

---

Simple CSS Loader.htm

This is a preview of the CSS Loader, it Rotates 360 degree.
please Merge my Request.

Added Simple CSS Loader

---

Aurora Animation.htm

This is a preview of Animated Aurora.

Added Aurora Animation.htm

---

Wave Loader Animation.htm

Added Wave Loader Animation

---

dijkstra's algorithm.cpp

Added Dijkstra's Algorithm  in C++ Language by Nrj-jr

Dijkstra's Algorithm

---

binary_search.cpp

I added binary search algorithm in C++.

Binary Search Algorithm

---

vectorBasic.cpp

vectorBasic.cpp please accept my PR, Akshat.

---

bracket_balance.c

Hey there,please review my PR.
Thank you.

Added bracket_balance.c

---

FibonacciNumbers.c
Imakshat47_binary2DecimalBasic.cpp
Imakshat47_binary2DecimalUsingInBuildFun.cpp
Imakshat47_binary2DecimalUsingString.cpp
Imakshat47_binary2Octal.cpp
Imakshat47_decimal2OctalBasic.cpp
Imakshat47_decimal2OctalFormula.cpp
Imakshat47_decimal2binaryBasicArray.cpp
Imakshat47_decimal2binaryBasicVoid.cpp
Imakshat47_decimal2binaryUsingBitwise.cpp
Imakshat47_octal2binary.cpp
binary2DecimalBasic.c
decimal2OctalBasic.c
decimal2OctalFormula.c
decimal2binaryBasicVoid.c
decimal2binaryUsingBitwise.c
octal2binary.c

Updates: Math Programs in C++

---

Armstrong in C

this code will take care of the numbers with number of digits=n (not just 3 digit number)

Update Armstrong in C

---

Floyd_Warshall.c
Recursive_Binary_Search.c

Added a program implementing Floyd Warshall algorithm in  C. The program contains enough comments to make it understandable.

'Floyd Warshall in C'

---

DetectLoop_UsingHash.java
ReverseLoop.java

I have added a Java program for detecting linked list loops using Hash in Java.

DetectLoopUsingHash-LinkedList

---

Remove all white spaces from a string with using replace().java

Program to remove all white spaces from a string with using replace()

Create Remove all white spaces from a string with using replace().java

---

coins.cpp
frog1.cpp
holi.cpp
journey.cpp
lcs.cpp
mixtures.cpp
pairing.cpp
topDown.cpp

Hey,
Added some dynamic programming codes in cpp.

Added dynamic programming cpp codes

---

pract9_vir_zip.py

Detecting .zip file in Network Packet.

---

FibonacciNumber.java
FibonacciNumber.php
FlippingBits.java
FlippingBits.php
Primality.java
Primality.php

Updates: Added Php and Java Programs

---

LeetCode Solutions/141. Linked List Cycle/141. Linked List Cycle.java
LeetCode Solutions/141. Linked List Cycle/Readme.md
LeetCode Solutions/142. Linked List Cycle II/142.linked-list-ii.java
LeetCode Solutions/142. Linked List Cycle II/Readme.md
LeetCode Solutions/15. 3sum/15.3sum.java
LeetCode Solutions/15. 3sum/Readme.md
LeetCode Solutions/442. Find All Duplicates in an Array/442. Find All Duplicates in an Array.java
LeetCode Solutions/442. Find All Duplicates in an Array/Readme.md
LeetCode Solutions/83. Remove Duplicates from Sorted List/83. Remove Duplicates from Sorted List.java
LeetCode Solutions/83. Remove Duplicates from Sorted List/Readme.md

I have added 5 more leetcode solutions to the repository. Hope this would be useful!

Added leetcode solutions

---

74.java- Search a matrix(Leetcode Problem)
Group Anagrams.java

Leetcode problem no-74
Search a 2D matrix (in java language)

Create 74.java- Search a 2D matrix(Leetcode Problem)

---

MST_Kruskals.cpp

I added a program on Kruskal's algorithm in CPP with explanations.

added Kruskal's algorithm

---

Fibonacci.java

Displays the Fibonacci sequence up to a certain number using recursion and memoization in Java

Create Fibonacci with memoization

---

CPP/intoToTutorialChallenges.cpp
CPP/simpleArraySum.cpp

programs in cpp

---

palindromicsubstring.py
removing_duplicates.cpp

count palindromic substrings in this string

Added Leetcode Palindromic Substrings solution

---

FibonacciNumber.py
FlippingBits.py
Primality.py

Updates: Added Python Flip Bit, Primality and Fibonacci Number Programs

---

Event Planner/eventplanner.html

Added event planner javascript app by dijodaiju7

Added event planner javascript app by dijodaiju7

---

java-programs/ThreadPoolPerformance.java

This is the thread pool project I am studying recently

ThreadPoolPerformance

---

LeetCode Solutions/1143. Longest Common Subsequence/LongCommSub.cpp
LeetCode Solutions/1143. Longest Common Subsequence/README.md
LeetCode Solutions/516. Longest Palindromic Subsequence/LongPalindSub.cpp
LeetCode Solutions/516. Longest Palindromic Subsequence/README.md

Added C++ Solution to said problem

1143. Longest Common Subsequence

---

Snake Game in cpp

Create Snake Game in cpp

---

LeetCode Solutions/Asteroid Collision

Solution for Asteroid Collision Leetcode By Abhinav Verma

Create Asteroid Collision

---

LeetCode Solutions/948. Bag Of Tokens/Readme
LeetCode Solutions/948. Bag Of Tokens/Solution For Bag Of Tokens
LeetCode Solutions/Bag Of Tokens

Leetcode C++ Solution added By Abhinav Verma

948. Bag Of Tokens

---

Map_Pattern_India

Map_Pattern_India

---

CPP/Longest_valid_parenthesis.cpp

Contributed longest valid parenthesis code

Longest_valid_parenthesis

---

global local scope

Create global local scope

---

accessing elements from array

Create accessing elements from array

---

CountingSort.py
RadixSort.py

Counting sort algorithm and Radix sort algorithm in python.

Added sorting algo

---

Clock.html
matrix multiplication.c

It's a program for Matrix Multiplication using C.

Create matrix multiplication.c
